title: Kieran's Blog  
author: KMC88
email: kpmcerlean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A blog...


twitter_username: @KieranMcErlean
github_username:  @KMC88

show_excerpts: false 

theme: jekyll-theme-minima 
